name: Publish release on tag creation

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  version:
    name: Verify that version is set  correctly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check release version is present in every file
        run: |
          for fname in setup.py CHANGELOG.rst docs/source/conf.py; do
            grep ${RELEASE_VERSION#v} ${fname}
          done

  release:
    name: Create a github release
    runs-on: ubuntu-latest
    environment: production
    needs:
      - tests
      - version
    steps:
      - uses: actions/checkout@v2

      - name: Get shortened version of release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 release_notes.py CHANGELOG.rst ${{ env.RELEASE_VERSION }} > release-notes.rst

          gh release create \
            ${{ env.RELEASE_VERSION}} \
            --notes-file release-notes.rst \
            --generate-notes

  publish:
    name: Publish package to pypi
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pypa/setuptools
        run: >-
          python -m
          pip install wheel

      - name: Build a binary wheel
        run: >-
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI }}
